Jax support
chandar-lab/RLHive pull request #265
Opened 2022-04-08 06:29 UTC by MHashemzadeh

Basic MLP and convolutional neural networks are created.

2022-04-11 18:05 UTC, dapatil211 requested changes

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/base.py
> +        return "function"
Delete

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/conv.py
> +@gin.configurable
delete

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/conv.py
> +import gin
delete

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/conv.py
> +from hive.agents.qnets.mlp import MLPNetwork
Shouldn't be here, it's torch

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/conv.py
> +        initializer = nn.initializers.xavier_uniform()
should be a parameter, either in this file or dqn file

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/conv.py
> +            conv_output_size = calculate_output_dim(self.conv, in_dim)
You'll probably need to write a jax version

2022-04-11 18:05 UTC, dapatil211 commented on hive/agents_jax/qnets/conv.py
> +from hive.agents.qnets.mlp import MLPNetwork
Should be jax version

2022-04-22 15:50 UTC, MHashemzadeh commented on hive/agents_jax/qnets/conv.py
> +import gin
It is deleted

2022-07-22 21:21 UTC, closed without merging