Remove MinatarEnv and use native Minatar gym wrapper
chandar-lab/RLHive pull request #266
Opened 2022-04-14 21:29 UTC by dapatil211

2022-05-19 19:59 UTC, sriyash421 commented
Merge conflict here. @dapatil211 miniatar.py is deleted in this pr and dev has some updates to it.

2022-05-24 19:12 UTC, alirahkay requested changes

2022-05-24 19:12 UTC, alirahkay commented on hive/configs/gym/random.yml
> +run_name: &run_name 'gym-random'
Please only put the PR-related changes into your PR. :)

2022-05-24 19:12 UTC, alirahkay commented on hive/configs/minatar/rainbow_circular_buffer.yml
> +    env_name: 'Breakout-v0'
I think this should be `MinAtar/Breakout-v0`. Am I right?

Based on the instructions given [here](https://github.com/kenjyoung/MinAtar#openai-gym-wrapper).

2022-05-24 19:12 UTC, alirahkay commented on hive/configs/minatar/dqn2.yml
> +# General training loop config
Also, what is the purpose of this file?

2022-06-27 20:05 UTC, dapatil211 commented
@alirahkay @sriyash421 , Fixed your concerns. Now this PR only deals with Minatar.

2022-06-27 20:12 UTC, alirahkay approved these changes
LGTM!

2022-06-27 21:33 UTC, sriyash421 approved these changes

2022-06-27 21:34 UTC, merged