Ddpg + TD3
chandar-lab/RLHive pull request #275
Opened 2022-05-03 23:28 UTC by dapatil211

Experiments are still being run to verify correctness, but please take a look and review. Closes #254

2022-05-05 15:18 UTC, dapatil211 commented
Results for runs on various mujoco environments with DDPG and TD3:
https://wandb.ai/chandar-rl/Hive/reports/DDPG-TD3-Results--VmlldzoxOTUzMTgx?accessToken=qsulda8jmwqcgtu32hz12m3thi1tdmwcuqizg9tgb2h4fgxwdz3f5mgzxfmlxhyh

They mostly match the cleanRL [benchmark](https://wandb.ai/cleanrl/cleanrl.benchmark/reports/Mujoco--VmlldzoxODE0NjE), our runs are slightly better in some cases.

2022-05-13 19:32 UTC, hnekoeiq commented on hive/agents/td3.py
> +        self._scale_actions = np.isfinite(self._action_scaling).all()
Handle `tanh` when self._action_max or self._action_min is not defined.

2022-05-13 19:47 UTC, hnekoeiq commented on hive/agents/qnets/td3_heads.py
> +        if self._n_critics == 1:
Do you need this condition?

2022-05-13 19:53 UTC, hnekoeiq commented on hive/agents/td3.py
> +            gamma=discount_rate,
Just a reminder that this should be done for other agents too.

2022-05-13 20:05 UTC, hnekoeiq commented on hive/agents/td3.py
> +        action = self.unscale_actions(np.expand_dims(action, axis=0))
Conditions have to be checked.

2022-05-24 18:59 UTC, alirahkay requested changes
Overall it looks good to me. 
I added my comment about the `tanh`. 

Also, as a final matter, did you run new experiments using the right number of testing episodes and add them to your WandB dashboard?

2022-05-24 18:59 UTC, alirahkay commented on hive/agents/ddpg.py
> +        action_space,
Why do these not have type annotations?

2022-05-24 18:59 UTC, alirahkay commented on hive/agents/qnets/td3_heads.py
> +        use_tanh=True,
You can just pass in the activation function (based on recent changes to dev). So this way gives more flexibility, and it's much more consistent with the current state of the codebase.

Something like, if the activation function is not None, then add that nonlinearity to the end of `actor_modules`.

2022-05-24 18:59 UTC, alirahkay commented on hive/agents/qnets/td3_heads.py
> +        network_output_shape,
Type annotations?

2022-05-25 16:44 UTC, dapatil211 commented on hive/agents/qnets/td3_heads.py
> +        use_tanh=True,
We kind of need it to be tanh because the action scaling relies on it being between -1 and 1

2022-06-27 19:53 UTC, dapatil211 commented
@alirahkay Runs are added to the baseline report with the correct number of test episodes. Added type annotations.
@hnekoeiq @sriyash421  if one of you could also review.

2022-06-27 20:14 UTC, alirahkay approved these changes
LGTM!

2022-07-07 19:08 UTC, sriyash421 commented on hive/agents/td3.py
> +            self._scale_actions,
I guess self._scale_actions specifies if we need to scale it i.e. use tanh right? Different variable names is causing some confusion.

2022-07-07 19:08 UTC, sriyash421 commented on hive/agents/td3.py
> +            "action": self.scale_action(update_info["action"]),
So the actor gives us an action between [-1,1] using tanh, but we unscale it to fit the action_space range, then for updating the buffer we scale down using the self.scale function. Two different scaling methods are used for the same thing. @dapatil211 this doesnt seem to be fully correct. My main concern is that do we return to exactly the same action values after the tanh, unscaling and scaling process.

2022-07-07 19:09 UTC, sriyash421 commented on hive/agents/td3.py
> +        for (network, target_network) in [
Should we add flags for hard/soft updates? Some works actually use them in their hyperparameter search

2022-07-13 16:05 UTC, sriyash421 commented on hive/agents/td3.py
> +            noise = torch.randn_like(action, requires_grad=False) * self._action_noise
No changes but a couple of comments.
1. File structure and naming has to be changed. I guess that can be handled  in a later PR.
2. Feature request here! Add an exploration class that can handle different exploration techniques? Uniform, gaussian, boltzmann

Rest everything looks good!

2022-07-13 16:06 UTC, sriyash421 approved these changes

2022-07-13 16:06 UTC, merged