Add num_updates_per_train_step hyperparameter
chandar-lab/RLHive pull request #276
Opened 2022-05-04 20:33 UTC by alirahkay

Previously we did not have this hyperparameter. It's needed in the Atari100K benchmark for the OverTrainedRainbow. The reason for adding to the general algorithms is that I think it's kind of an important hyperparameter in RL algorithms in general.  I'll be glad to hear your comments on this.

2022-05-04 20:54 UTC, dapatil211 requested changes
You also need to add the parameter to legal_moves_rainbow.

2022-05-04 20:54 UTC, dapatil211 commented on hive/agents/dqn.py
> +            num_updates_per_train_step (int): indicates the number of consecutive times the agent needs to
Fix line length. Should be less than 88

2022-05-04 20:54 UTC, dapatil211 commented on hive/agents/rainbow.py
> +            num_updates_per_train_step (int): indicates the number of consecutive times the agent needs to
fix line length

2022-05-04 20:54 UTC, dapatil211 commented on hive/agents/rainbow.py
> +                    )
This will cause issues. logger.should_log does not update the step. So a bunch of training losses will be logged at the same step. Solution is to either aggregate them (as numpy) and log them outside, or update the step in the internal loop. I think I prefer the aggregation solution. Same issue for DQN.

2022-05-19 18:03 UTC, alirahkay commented
I'd close this for now; we can pick it up later.

2022-05-19 18:03 UTC, closed without merging