Create rliable.py
chandar-lab/RLHive pull request #287
Opened 2022-05-25 18:30 UTC by Rahul-Choudhary-3614

2022-05-27 18:34 UTC, dapatil211 requested changes
Ple

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +MEDIAN = lambda x: metrics.aggregate_median(x)
There's no reason to put these outside. You can just use the functions directly

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +import argparse
Sort imports with isort (your editor likely already has functionality for this)

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +import argparse
Sort imports with isort (your editor likely already has functionality for this)

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +def load_and_read_rewards(env_names,path,min_env_score,max_env_score,Normalization):
normalization should be lowercase

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +    score_ = np.load(path+'/'+env_name+'/Rewards.npy')
1. Use os.path.join
2. Where are you getting this file name from? You should be loading the rewards from the chomplogger files.

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +      score_dict[env_name] = score_normalization(score_, min_env_score[env_index], max_env_score[env_index])
min_env_score is a scalar isn't it?

2022-05-27 18:34 UTC, dapatil211 commented on hive/utils/rliable.py
> +  if plot:
Hold off on this for now. We can add it once we have a good way of getting the raw metrics

2022-06-15 21:37 UTC, dapatil211 requested changes

2022-06-15 21:37 UTC, dapatil211 commented on hive/utils/rliable_matrix.py
> +    # print('Probabilities {}'.format(probabilities))
Delete commented code

2022-06-15 21:37 UTC, dapatil211 commented on hive/utils/rliable_matrix.py
> +    # Higher value of reps corresponds to more accurate estimates but are slower to computed. `reps` corresponds to number of bootstrap resamples.
longer than 88 columns

2022-06-15 21:37 UTC, dapatil211 commented on hive/utils/rliable_matrix.py
> +    """
Longer than 88 columns

2022-06-15 21:37 UTC, dapatil211 commented on hive/utils/rliable_matrix.py
> +                        "logger/logger_0/log_data.p",
You should not assume you have this file structure. For now, write the functions in the following way:
`process_rewards(rewards)`, where rewards is whatever format/structure you want (ie assume the data has already been loaded for you. Then write a separate function to read the rewards. For this, you can use the functions in `visualization.py` if that's easier (eg something like `find_all_experiments_data()` and you just write code to pass the appropriate arguments.

2022-07-12 17:05 UTC, Prishruit commented
@Rahul-Choudhary-3614 could you update the code so that it is consistent with the current base branch.

2022-07-22 21:21 UTC, closed without merging