WIP: Remove AtariEnv
chandar-lab/RLHive pull request #334
Opened 2023-04-03 20:16 UTC by artemZholus

2023-04-21 19:07 UTC, artemZholus commented
The PR is now ready for review!

2023-05-01 19:30 UTC, dapatil211 requested changes

2023-05-01 19:30 UTC, dapatil211 commented on hive/configs/atari/dqn.yml
> +        - name: PermuteImageWrapper
Just add a comment here saying that this converts from channels last (TF format) to channels first (Pytorch format)

2023-05-03 15:08 UTC, artemZholus commented on hive/configs/atari/dqn.yml
> +        - name: PermuteImageWrapper
Fixed!

2023-05-04 12:57 UTC, kshitijkg approved these changes

2023-05-05 20:15 UTC, mrsamsami approved these changes

2023-05-19 19:01 UTC, dapatil211 approved these changes

2023-05-19 19:05 UTC, merged