Added SAC agents
chandar-lab/RLHive pull request #337
Opened 2023-04-12 20:29 UTC by dapatil211

2023-05-03 15:25 UTC, hnekoeiq requested changes
Some minor comments. Otherwise, LGTM. Could you also add the link to the results?

2023-05-03 15:25 UTC, hnekoeiq commented on hive/agents/qnets/sac_heads.py
> +    the :obj:`actor_net`, and adds creates a
typo?

2023-05-03 15:25 UTC, hnekoeiq commented on hive/configs/mujoco/sac.yml
> +
remove?

2023-05-03 15:25 UTC, hnekoeiq commented on hive/agents/sac.py
> +        # action = action
What this comment is for?

2023-05-03 16:27 UTC, dapatil211 commented
Link to results comparing with CleanRL: https://api.wandb.ai/links/dapatil211/1df29fog

2023-05-17 14:11 UTC, alirahkay approved these changes
LGTM

2023-05-17 14:20 UTC, hnekoeiq approved these changes

2023-05-17 14:21 UTC, merged